### ISSUE TITLE
instructions miss `cd my-notes-app`

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/react-graphql-template#21]
https://blog.holochain.org/holochain-dev-pulse-67-bootstrap-a-happ-in-one-command/?utm_source=hootsuite&utm_medium=&utm_term=&utm_content=&utm_campaign=

need to cd into the app after creating it

**Comment by robbiecarlton** [comment]
I see the `$ cd my-notes-app` in those instructions. Maybe they've been updated since you looked.

**Comment by philipbeadle** [comment]
Article has been updated
