### ISSUE TITLE
instructions say to clone the whole holonix repo just to get a shell

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/react-graphql-template#22]
https://blog.holochain.org/holochain-dev-pulse-67-bootstrap-a-happ-in-one-command/?utm_source=hootsuite&utm_medium=&utm_term=&utm_content=&utm_campaign= 

```
git clone https://github.com/holochain/holonix.git && cd holonix && git checkout develop && nix-shell
```

don't need all this, just need:

```
nix-shell https://github.com/holochain/holonix/archive/develop.tar.gz
```

which has several benefits:

- less typing
- easier to remember
- doesn't keep a permanent clone kicking around in a random directory
- pulls a tarball of the tip of develop instead of a clone of the entire git history
- can be run anywhere and keeps a cache of the download inside nix

**Comment by robbiecarlton** [comment]
@pdaoust - can you update the instructions to reflect this?

**Comment by pdaoust** [comment]
sweet, thanks! Will share. @thedavidmeister for clarification, `nix-shell` just recognises any archive with a `default.nix` file in its root (in this case a snapshot of the `develop` branch), is that right?

**Comment by pdaoust** [comment]
Updated readme, discovered someone else had already done it, resolved merge conflict, and updated [blog](https://blog.holochain.org/holochain-dev-pulse-67-bootstrap-a-happ-in-one-command/) and [forum](https://forum.holochain.org/t/try-out-the-first-prototype-of-our-new-scaffolding-tool/2471) posts.

**Comment by thedavidmeister** [comment]
@pdaoust yeah, when you hit a tarball URL nix looks for a default.nix file

unfortunately it doesn't respect shell.nix files when using a URL (last time i checked), which accounts for about half our boilerplate :P
