### ISSUE TITLE
error: hash mismatch in file

### ISSUE THREAD

**Issue by nerdfiles** [holochain/react-graphql-template#26]
also, L3 is not sha256:
https://github.com/holochain/react-graphql-template/blob/a8b0afc82e043f47bc9c69df3a76262d7bd38133/dna_src/default.nix#L2-L3

**Comment by pdaoust** [comment]
@nerdfiles good point; it's a SHA1 hash to a git commit https://github.com/holochain/holonix/commit/507d64923640221bbc8ca096fbac4e1d30da7a97 . The proper sha256 for the v0.0.71 release is `1jav1sr3kh1f204rarcis8cm59fwbapg8wqnp9dpyz7c5kvhkwnx`. I'm also seeing a space at the end of the release tag string, which should cause it to fail.

Question: whereabouts are you using this? Are you `cd`ing into the `dna_src` dir and running `nix-shell` without any params?

**Comment by pdaoust** [comment]
Oh, looks like this was resolved by https://github.com/holochain/react-graphql-template/pull/25 -- totally different nix config files.
